Implemented Remaining Catalog operations for REST catalog
apache/iceberg-go pull request #240
Opened 2024-12-30 11:39 UTC by chil-pavn

Part of #63 . Tried implementing createTable, dropTable and renameTable methods taking reference to loadTable and rest-catalog-open-api.

2024-12-30 16:19 UTC, zeroshade commented
@chil-pavn In general this is looking good, I'll give it a more in-depth review in the next couple days. Could you add some unit tests for these as we have for the other functions? (basically just mocking out the server responses with a local http server)

2024-12-30 16:25 UTC, piyushsingariya requested changes
be verbose with naming conventions until not necessary.

2024-12-30 16:25 UTC, piyushsingariya commented on catalog/rest.go
> +	}
```suggestion
	fromNamespace, fromTable, err := splitIdentForPath(from)
	if err != nil {
		return nil, err
	}

	toNamespace, toTable, err := splitIdentifierForPath(to)
	if err != nil {
		return nil, err
	}
```

2024-12-30 16:25 UTC, piyushsingariya commented on catalog/rest.go
> +	}
```suggestion
	namespace, table, err := splitIdentifierForPath(identifier)
	if err != nil {
		return nil, err
	}
```

2024-12-30 16:25 UTC, piyushsingariya commented on catalog/rest.go
> +	tblProps := maps.Clone(r.props)
```suggestion
	tableProperties := maps.Clone(r.props)
```

2025-01-02 19:47 UTC, zeroshade commented on README.md
> -$ cd iceberg-go/cmd/iceberg && go build .
Why is this being removed?

2025-01-03 01:59 UTC, chil-pavn commented on README.md
> -$ cd iceberg-go/cmd/iceberg && go build .
Ahhh ! my bad. This wasn't intended.

2025-01-03 02:12 UTC, chil-pavn commented on catalog/rest.go
> +	}
@piyushsingariya splitIdentForPath is called in many other places in the codebase. I don't think doing that would help.

2025-01-03 02:17 UTC, chil-pavn commented on catalog/rest.go
> +	}
I agree that the suggestions are more detailed. But ns, tbl, and Props are consistently used throughout the codebase

2025-01-03 18:07 UTC, zeroshade commented on catalog/rest.go
> +	}
any reason not to create a struct for this instead of the maps?

2025-01-03 18:08 UTC, zeroshade commented on catalog/rest.go
> +	}
`maps.Copy(tblProps, ret.Config)`?

2025-01-08 17:05 UTC, chil-pavn commented
Hey @zeroshade , it appears there was already PR #146 for the same table operations, which also got merged. Should i work on the unit tests, as i could see that was not included in the PR?

2025-01-08 17:09 UTC, zeroshade commented
@chil-pavn that would be fantastic thanks!

2025-01-08 17:14 UTC, chil-pavn commented
@zeroshade Sure, I will take that up. Also, it would be very helpful if i we link PRs to the respected issues.

2025-01-15 10:21 UTC, closed without merging

2025-01-15 10:21 UTC, chil-pavn commented
hey @zeroshade i am closing this pull request as i don't think it is any more relevant. Will open a new PR for the unit tests.